### PR TITLE
Meaningful error message for wrong account name

### LINKED ISSUE #52: Error message is not meaningful when wrong account name used
If the user specifies the wrong account name, then the `chaosmonkey eligible` command yields the following error:

```
spinnaker@hal-123:~$ chaosmonkey eligible sireeapp1 spinnaker-service-account
retrieve cloud provider failed: json unmarshal failed: unexpected end of JSON input
```

This error message doesn't provide the user with information about what the problem and how to fix it. Chaos Monkey should provide a more meaningful error message in this scenario.

See #50 and #51.

### PR DESCRIPTION
**Pull request by prytoegrian**
Fix #52 

```sh
spinnaker@hal-123:~$ chaosmonkey eligible sireeapp1 {wrongAccountName}
retrieve cloud provider failed: json unmarshal failed: unexpected end of JSON input
```

## Why 
Behind the curtain, `eligible` asks for the CloudProvider name associated to the user typed. For getting this information, one calls the `/credentials/{wrongAccountName}` spinnaker API route. But, obviously, this route doesn't exist. The flaw occurs in this case, and the app can't distinguish the events : 
* the JSON response is malformed,
* there's no user with this name.

## Technical solution
I used [another route](https://github.com/spinnaker/gate/blob/921285f4f02ed5ebc46411ec100459d171292fbd/gate-core/src/main/groovy/com/netflix/spinnaker/gate/services/internal/ClouddriverService.groovy#L37L44) proposed by the API. This route returns all accounts attached to the instance, and I simply check if `{wrongAccountName}` is present for displaying a good error message.

---

~~NB1 : My last changes weren't verified as deeply as I used to do. I broke my test VM instance before finishing so let me know if you want me to repair it before review and test or if we start the review now.~~
NB2 : I'm not an expert in Golang so do not hesitate to criticise, I want to improve my knowledges.

### CODE REVIEW

**Comment by lorin** [comment]
@prytoegrian The PR title says WIP. Is this still in progress or is it ready for review?

**Comment by prytoegrian** [comment]
Ready for review !

File: spinnaker/spinnaker.go [hunk 1]
```diff
@@ -479,12 +479,35 @@ func (s Spinnaker) asgs(appName, account, clusterName string) (result []spinnake
...
-	url := s.accountURL(account)
+// CloudProvider returns the cloud provider for a given account name
+func (s Spinnaker) CloudProvider(name string) (provider string, err error) {
+	account, err := s.account(name)
+	if err != nil {
+		return "", err
+	}
+
+	if account.CloudProvider == "" {
+		return "", fmt.Errorf("no cloudProvider field in response body")
```
Comment (ecamillerifyusion) [inline spinnaker/spinnaker.go]: If you don't need to format your return error, `errors.new("")` will be fine :)

Comment (prytoegrian) [reply spinnaker/spinnaker.go]: Thanks !

**Comment by prytoegrian** [comment]
cc @lorin :-)

File: spinnaker/spinnaker.go [hunk 2]
```diff
@@ -479,12 +479,35 @@ func (s Spinnaker) asgs(appName, account, clusterName string) (result []spinnake
...
+
+// account returns an account by its name
+func (s Spinnaker) account(name string) (*account, error) {
+	url := s.accountsURL(true)
 	resp, err := s.client.Get(url)
+
+	// Usual HTTP checks
 	if err != nil {
-		return "", errors.Wrap(err, fmt.Sprintf("http get failed at %s", url))
+		return nil, errors.Wrap(err, fmt.Sprintf("http get failed at %s", url))
```
Comment (oleg-balunenko) [inline spinnaker/spinnaker.go]: suggest to use `errors.Wrapf()` and not use fmt.Sprintf for error message creating
https://godoc.org/github.com/pkg/errors#Wrapf

File: spinnaker/spinnaker.go [hunk 3]
```diff
@@ -495,32 +518,33 @@ func (s Spinnaker) CloudProvider(account string) (provider string, err error) {
 
 	body, err := ioutil.ReadAll(resp.Body)
 	if err != nil {
-		return "", errors.Wrap(err, fmt.Sprintf("body read failed at %s", url))
-	}
-
-	var fields struct {
-		CloudProvider string `json:"cloudProvider"`
-		Error         string `json:"error"`
+		return nil, errors.Wrap(err, fmt.Sprintf("body read failed at %s", url))
```
Comment (oleg-balunenko) [inline spinnaker/spinnaker.go]: the same about errors.Wrapf

File: spinnaker/spinnaker.go [hunk 4]
```diff
@@ -495,32 +518,33 @@ func (s Spinnaker) CloudProvider(account string) (provider string, err error) {
...
-		if fields.Error == "" {
-			return "", fmt.Errorf("unexpected status code: %d. body: %s", resp.StatusCode, body)
+	// Finally find account
+	for _, a := range accounts {
+		if a.Name != name {
+			continue
 		}
+		if statusKO {
+			if a.Error == "" {
+				return nil, fmt.Errorf("unexpected status code: %d. body: %s", resp.StatusCode, body)
```
Comment (oleg-balunenko) [inline spinnaker/spinnaker.go]: suggest to be consistent in errors creation.
Use errors.Errorf instead
https://godoc.org/github.com/pkg/errors#Errorf

File: spinnaker/spinnaker.go [hunk 5]
```diff
@@ -495,32 +518,33 @@ func (s Spinnaker) CloudProvider(account string) (provider string, err error) {
...
+			}
 
-		return "", fmt.Errorf("unexpected status code: %d. error: %s", resp.StatusCode, fields.Error)
-	}
+			return nil, fmt.Errorf("unexpected status code: %d. error: %s", resp.StatusCode, a.Error)
```
Comment (oleg-balunenko) [inline spinnaker/spinnaker.go]: Use errors.Errorf instead

File: spinnaker/spinnaker.go [hunk 6]
```diff
@@ -495,32 +518,33 @@ func (s Spinnaker) CloudProvider(account string) (provider string, err error) {
...
-	}
-
-	var fields struct {
-		CloudProvider string `json:"cloudProvider"`
-		Error         string `json:"error"`
+		return nil, errors.Wrap(err, fmt.Sprintf("body read failed at %s", url))
 	}
 
-	err = json.Unmarshal(body, &fields)
+	accounts := make([]account, 0)
```
Comment (oleg-balunenko) [inline spinnaker/spinnaker.go]: var accounts []account

**Comment by prytoegrian** [comment]
Thanks @oleg-balunenko, i'll fix that as soon as I can.

**Comment by prytoegrian** [comment]
Thanks @oleg-balunenko !
@lorin good for review.

**Comment by lorin** [comment]
Looks good to me. @aplsek, can you take a look?

**Comment by aplsek** [comment]
Yes, let me take a look.

File: spinnaker/spinnaker.go [hunk 7]
```diff
@@ -479,12 +479,35 @@ func (s Spinnaker) asgs(appName, account, clusterName string) (result []spinnake
...
+	Name          string `json:"name"`
+	Error         string `json:"error"`
+}
+
+// account returns an account by its name
+func (s Spinnaker) account(name string) (*account, error) {
+	url := s.accountsURL(true)
 	resp, err := s.client.Get(url)
+
+	// Usual HTTP checks
```
Comment (aplsek) [inline spinnaker/spinnaker.go]: Nit: It seems like it was not in the original code either but I believe after this error check we should also call `defer resp.Body.Close()`.

File: spinnaker/spinnaker.go [hunk 8]
```diff
@@ -479,12 +479,35 @@ func (s Spinnaker) asgs(appName, account, clusterName string) (result []spinnake
...
+
+// account represents a spinnaker account
+type account struct {
+	CloudProvider string `json:"cloudProvider"`
+	Name          string `json:"name"`
+	Error         string `json:"error"`
+}
+
+// account returns an account by its name
+func (s Spinnaker) account(name string) (*account, error) {
```
Comment (oleg-balunenko) [inline spinnaker/spinnaker.go]: Are you plan to update the `account` returned here? Pointers serve one purpose, to share a value with a function so the function can read and write to that value even though the value does not exist directly inside its own frame
If you don't need to share - prefer to see value semantics. Each time when function receive or return pointers - this causes memory allocation on heap.

File: spinnaker/spinnaker.go (hunk 7 above)
Comment (prytoegrian) [reply spinnaker/spinnaker.go]: Finally, I'm not sure what you're asking me, there's already a `defer resp.Body.Close()` in [l.513](https://github.com/Netflix/chaosmonkey/pull/56/files/1f5bf2551919a0e87f6723e491cde2895413f765#diff-7df64bbe98f3aaa527a08ee3baac15afR513). Did I miss something ?

File: spinnaker/spinnaker.go (hunk 8 above)
Comment (prytoegrian) [reply spinnaker/spinnaker.go]: Understood. Here, `account` is a pointer because of the `nil` case : when there's an error, I return no `account` value. I must admit that I have never proceed otherwise.

Is this a good solution ? Are there any best practices for these throwable vars ?

```diff
// account returns an account by its name
func (s Spinnaker) account(name string) (account, error) {
	url := s.accountsURL(true)
	resp, err := s.client.Get(url)
+	var ac account

	// Usual HTTP checks
	if err != nil {
+		return ac, errors.Wrapf(err, "http get failed at %s", url)
	}

	defer func() {
		if cerr := resp.Body.Close(); cerr != nil && err == nil {
			err = errors.Wrap(err, fmt.Sprintf("body close failed at %s", url))
		}
	}()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
+		return ac, errors.Wrapf(err, "body read failed at %s", url)
	}

	var accounts []account
	err = json.Unmarshal(body, &accounts)
	if err != nil {
+		return ac, errors.Wrap(err, "json unmarshal failed")
	}
	statusKO := resp.StatusCode != http.StatusOK

	// Finally find account
	for _, a := range accounts {
		if a.Name != name {
			continue
		}
		if statusKO {
			if a.Error == "" {
+				return ac, errors.Errorf("unexpected status code: %d. body: %s", resp.StatusCode, body)
			}

+			return ac, errors.Errorf("unexpected status code: %d. error: %s", resp.StatusCode, a.Error)
		}

		return a, nil
	}

+	return ac, errors.New("the account name doesn't exist")
}
```

File: spinnaker/spinnaker.go (hunk 7 above)
Comment (aplsek) [reply spinnaker/spinnaker.go]: Ohh, yes! Its there. I must have missed it!

File: spinnaker/spinnaker.go (hunk 8 above)
Comment (aplsek) [reply spinnaker/spinnaker.go]: I am fine with either but looking at the other parts of the code, it seems like the value semantics are indeed preferred for those cases where type is used locally to just pass a group of values between a couple of methods.

I would not worry about performance or heap-optimizations

**Comment by prytoegrian** [comment]
Tadaaa :tada:

**Comment by prytoegrian** [comment]
:slightly_smiling_face:
